[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Nikhilesh Singh <nikhilesh2010@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.1"
scoped_threadpool = "0.1.*"
